name: Build LiveBuilder

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        
    - name: Build
      run: |
        go mod download
        go build -ldflags="-s -w" -o LiveBuilder-linux-amd64
        
    - name: Upload Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: LiveBuilder-linux-amd64
        path: LiveBuilder-linux-amd64

  build-macos-intel:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Build for Intel Mac
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: |
        go mod download
        go build -ldflags="-s -w" -o LiveBuilder-darwin-amd64
        
    - name: Create Intel Mac app bundle
      run: |
        mkdir -p LiveBuilder-Intel.app/Contents/MacOS
        cp LiveBuilder-darwin-amd64 LiveBuilder-Intel.app/Contents/MacOS/LiveBuilder
        
        cat > LiveBuilder-Intel.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>LiveBuilder</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourcompany.livebuilder</string>
            <key>CFBundleName</key>
            <string>LiveBuilder</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
        </dict>
        </plist>
        EOF
        
        chmod +x LiveBuilder-Intel.app/Contents/MacOS/LiveBuilder
        
    - name: Upload Intel Mac app
      uses: actions/upload-artifact@v4
      with:
        name: LiveBuilder-Intel-Mac
        path: LiveBuilder-Intel.app/

  build-macos-silicon:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Build for Apple Silicon Mac
      env:
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: arm64
      run: |
        go mod download
        go build -ldflags="-s -w" -o LiveBuilder-darwin-arm64
        
    - name: Create Apple Silicon Mac app bundle
      run: |
        mkdir -p LiveBuilder-Silicon.app/Contents/MacOS
        cp LiveBuilder-darwin-arm64 LiveBuilder-Silicon.app/Contents/MacOS/LiveBuilder
        
        cat > LiveBuilder-Silicon.app/Contents/Info.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>LiveBuilder</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourcompany.livebuilder</string>
            <key>CFBundleName</key>
            <string>LiveBuilder</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
        </dict>
        </plist>
        EOF
        
        chmod +x LiveBuilder-Silicon.app/Contents/MacOS/LiveBuilder
        
    - name: Upload Apple Silicon Mac app
      uses: actions/upload-artifact@v4
      with:
        name: LiveBuilder-Apple-Silicon-Mac
        path: LiveBuilder-Silicon.app/