name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Test build
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Go version:"
        go version
        echo "Attempting build:"
        go mod download
        go build -o LiveBuilder-test
        ls -la LiveBuilder-test
        
    - name: Upload test binary
      uses: actions/upload-artifact@v4
      with:
        name: test-binary
        path: LiveBuilder-test